### ISSUE TITLE
Checking interest form 

### ISSUE THREAD

**Issue by davispolito** [mzero/pulsar-buddy#1]
Hi, I believe I submitted an interest form awhile back but just wanted to check and make sure because I haven’t received any update email. 

My email is davispolito1@gmail.com
Thanks!

**Comment by mzero** [comment]
No problem! You are on the list - I've been really behind, the recent
response has been a bit overwhelming! Enough so that I've got to go set up
a mailing list account, etc...!  I'll try to get a status e-mail out this
week. In short - first batch is totally sold out (yay!) - and I'm trying to
get boards to the fabrication house ASAP so that we'll have a second batch
by early Summer - say mid-July.

- Mark

**Comment by davispolito** [comment]
Well I bet that’s great news! I’m glad the project is going well. I love
the emphasis the pulsar puts on weird rhythms and stuff. I look forward to
getting mine and pairing it with the subharmonicon and your pulsar buddy!

How long have you been working with electronics ?
